### PR TITLE
Removal of Vulnerable Dependencies

### LINKED ISSUE #30: Some Dependencies Contain Vulnerabilities
Some Maven dependencies contain known CVEs. We should upgrade the dependencies to the latest patched versions and validate.

### PR DESCRIPTION
**Pull request by dwseiber**
closes #30.

### CODE REVIEW

**Comment by ilipkind** [comment]
@dwseiber There are few problems with this PL:

1. Please add me (ilipkind) to your source repo as Reader: dwseiber:insecure_dependency_updates. I want to compile it before approving merge or move your fork to public.

2. Please bump up minor version from 3.3.1-SNAPSHOT to 3.3.2-SNAPSHOT

**Comment by dwseiber** [comment]
Absolutely. I'll do that now. What is the process for updating GE Artifactory?

**Comment by ilipkind** [comment]
@dwseiber running a build now: https://predix1.jenkins.build.ge.com/job/Predix-Security/job/token-lib/job/token-lib-build-n-test-dev/92/console it should promote to internal artifactory

**Comment by ilipkind** [comment]
the JAR is promoted to artifactory: https://devcloud.swcoe.ge.com/artifactory/predix-virtual/com/ge/predix/uaa-token-lib/3.3.2-SNAPSHOT/ @dwseiber do you need to merge it to master or SNAPSHOT version is sufficient?

**Comment by dwseiber** [comment]
If possible I would like it merged to master, as we would like to depend on the non-snapshot artifact.

**Pull request merged**
